import { HTML_INTRODUCTION,HTML_TABLE_TAGS,HTML_HEADINGS_TAGS, HTML_HORIZONTAL_RULE,HTML_TEXT_FORMAT_TAGS,HTML_FONT_TAGS, HTML_IMAGE_TAGS, HTML_LIST_TAGS, HTML_MARQUEE_TAGS, HTML_ANCHOR_TAGS } from './html';




export const pageContent = [
    HTML_INTRODUCTION,
    HTML_HEADINGS_TAGS,
    HTML_HORIZONTAL_RULE,
    HTML_TEXT_FORMAT_TAGS,
    HTML_FONT_TAGS,
    HTML_IMAGE_TAGS,
    HTML_TABLE_TAGS,
    HTML_LIST_TAGS,
    HTML_MARQUEE_TAGS,
    HTML_ANCHOR_TAGS
];